imports:
    - { resource: parameters.yml }

doctrine:
    orm:
        dql:
            numeric_functions:
                rand: DoctrineExtensions\Query\Mysql\Rand

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'

    App\Service\Config\YoutubeConfig:
        arguments:
            $apiKey: '%youtube_api_key%'
            $baseUri: '%youtube_api_base%'
